### ISSUE TITLE
[question] template inheritance vs freemarker macros

### ISSUE THREAD

**Issue by DaimonPl** [kwon37xi/freemarker-template-inheritance#4]
Freemarker has built in support for macros which allow to achieve (kind of) template inheritance:

**macros**

```
<#-- base.ftl -->
<#macro content></#macro>

<#macro display_page>
<html>
<body>
    <@content/>
</body>
</html>
</#macro>

```

```
<#-- child.ftl -->
<#include "base.ftl">

<#macro content>
    Example content
</#macro>

<@display_page/>
```
**kwon37xi inheritance**

```
<#-- base.ftl -->
<html>
<body>
    <@layout.block name="header"></@layout.block>
</body>
</html>
```

```
<#-- child.ftl -->
<@layout.extends name="base.ftl">
    <@layout.put block="contents">
        Example content
    </@layout.put>
</@layout.extends>
```

**QUESTION**

Although kwon37xi inheritance contains nicer markup and some additional features like append/prepend is there any other advantage to use kwon37xi inheritance instead of macros? Have you tried any performance tests etc?

This would be good topic to extend Readme as well

**Comment by kwon37xi** [comment]
I don't think freemarker-template-inheritance(FTI) is faster than macro. Actually I haven't tested about the performance of FTI.
Anyway this is used for a service which has over 15 million users(I'm working for the service).

I think the pros of FTI are
* with FTI, multiple inheritance is possible
* People just recognize this is about layout when they see the "<@layout:xxx>" tags. With macros people may have to think what the macros mean.
