### ISSUE TITLE
freemarker template inheritance support “super” keyword?

### ISSUE THREAD

**Issue by mynameisshiy** [kwon37xi/freemarker-template-inheritance#5]
like python framework jinja2 ？

**Comment by kwon37xi** [comment]
I don't exactly know what 'super()' does in jinja2.
Anyway I think the following is similar.

<@layout.put type="APPEND|PREPEND|REPLACE"> type has 3 options.
- APPEND : The put contents will be appended after block's contents. default.
- PREPEND : The put contents will be prepended before block's contents.
- REPLACE : The put contents will replace block's contents. The block's contents will be removed.

You may try APPEND or PREPEND for {{super()}} like thing.

**Comment by mynameisshiy** [comment]
That is it。tks！
