### ISSUE TITLE
extends not work?

### ISSUE THREAD

**Issue by mynameisshiy** [kwon37xi/freemarker-template-inheritance#6]
hi.
I have a web, include 3 page.the relationship as shown below:
A.ftl is base、B.ftl extend A.ftl、C.ftl extend B.ftl。
A.ftl and  B.ftl normal work，but the C.ftl didn't work。
thx.

**Comment by kwon37xi** [comment]
Show me the code please.

**Comment by mynameisshiy** [comment]
[zip.zip](https://github.com/kwon37xi/freemarker-template-inheritance/files/191372/zip.zip)

**Comment by kwon37xi** [comment]
There is no block in index.ftl.
If you want some ftl to be layout template, there must be `<@layout.block>`

**Comment by mynameisshiy** [comment]
That is to say Multi-level inheritance not yet supported.
If i want reg.ftl use <@layout.put block> in base.ftl some block ,then I must put the block in index.ftl?

**Comment by kwon37xi** [comment]
Yes, you're right.

**Comment by mynameisshiy** [comment]
OK，thanks
