### ISSUE TITLE
How to pass parameters to a subpage and security tag ?

### ISSUE THREAD

**Issue by ncc0706** [kwon37xi/freemarker-template-inheritance#7]
**This is dashboard.html page code**
```
      <!-- main area -->
      <div class="main-content">
        <#assign message="This is message"/>
      	<@layout.block name="content">
               <!--This is ok.-->
      		${message}
      	</@layout.block>
      </div>
      <!-- /main area -->
```
**This is subpage code.**
``` 
<@layout.put block="content">
<!--this tag only write subpage !!!-->
<#assign  security=JspTaglibs["/WEB-INF/tlds/security.tld"] />
<div class="row">
<div class="panel panel-default">
    <div class="panel-body">
    	     <!--This is bad-->
             ${message}
	    <@security.authorize access="hasRole('ADMIN')">
		login as admin
	     </@security.authorize>
    </div>
</div>
</div>
</@layout.put>
<@layout.extends name="layouts/dashboard.html" />
```

**Comment by kwon37xi** [comment]
I don't get what you exactly want.
If you are using Spring MVC and have any data to pass to subpage, just use ModelAndView.addAttribute().

**Comment by ncc0706** [comment]
Sorry. My English is poor.
Yes  SpringMVC is ok.

**first**
freemarker <#assign message="This is message"/> not useing subpage 
like this
```
<@layout.put block="content">
${message}
</@layout.put>
<@layout.extends name="layouts/dashboard.html" />
```

**second**
<#assign  security=JspTaglibs["/WEB-INF/tlds/security.tld"] /> the same not useing subpage
```
<@security.authorize access="hasRole('ADMIN')">
login as admin
</@security.authorize>
```

[code: https://github.com/ncc0706/dashboard](https://github.com/ncc0706/dashboard)

Thanks.

**Comment by kwon37xi** [comment]
`<#assign>` affect only in the same ftl file.
please refer to http://freemarker.org/docs/ref_directive_assign.html
If you have any data shared among layouts, use `ModelAndView.addAttribute()`.

**Comment by ncc0706** [comment]
Ok, I see .
``<#assign security=JspTaglibs["/WEB-INF/tlds/security.tld"] />`` must write subpage??

**Comment by kwon37xi** [comment]
Yes.
